### ISSUE TITLE
Error while deploying to Azure App Service

### ISSUE THREAD

**Issue by krishnaspmoorthy** [microsoftgraph/windowsupdates-webapplication-sample#5]
Hi,

I am trying to deploy this to Node.js app service which is running on ubuntu-latest with 16 LTS. Getting the below error when starting the npm.

> wufbdswebapp@0.1.0 start /home/site/wwwroot
> webpack-dev-server .

/home/site/wwwroot/node_modules/webpack-dev-server/lib/Server.js:2557
        throw error;
        ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at READ_WRITE (/home/site/wwwroot/node_modules/webpack-dev-server/lib/Server.js:3365:23)
    at new Promise (<anonymous>)
    at Server.start (/home/site/wwwroot/node_modules/webpack-dev-server/lib/Server.js:3363:7)
    at async Command.<anonymous> (/home/site/wwwroot/node_modules/@webpack-cli/serve/lib/index.js:158:21)
    at async Command.parseAsync (/home/site/wwwroot/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async Command.<anonymous> (/home/site/wwwroot/node_modules/webpack-cli/lib/webpack-cli.js:1304:13)
    at async Command.parseAsync (/home/site/wwwroot/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wufbdswebapp@0.1.0 start: `webpack-dev-server .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wufbdswebapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-05-22T09_19_11_835Z-debug.log

I tried with a different port in the webpack config file. I think the service is starting and getting index.html when doing the curl, but the page is not coming.

Please help to resolve this.

Thank you.

regds,
Krishna.

**Comment by Ryan-K-Williams** [comment]
Hello Krishna,

It seems that port 3000 is in use.  Can you check what is running on port 3000 using command: `lsof -i :3000`

Either stop what is running on port 3000 or configure it to run on an unused port.  If you change the port you'll have to update the app configuration under Configure Authentication and Permissions to use the port you selected in the redirect URIs.  Example: http://localhost:**3000**/

**Comment by Ryan-K-Williams** [comment]
This sample has been archived and is no longer being maintained.  As part of the archival process, we're closing all open issues and pull requests.
